version: 2.1

orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.1.3

jobs:
  docker:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      # with credentials stored in the UI
      - run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      # build the application image
      - run: docker build -t $DOCKER_USERNAME/joke-api:$CIRCLE_BRANCH .

      # deploy the image
      - run: docker push $DOCKER_USERNAME/joke-api:$CIRCLE_BRANCH

workflows:
  build-test:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - ci
      - node/test:
          requires:
            - "node/run"
          filters:
            branches:
              only:
                - ci
      - docker:
          requires:
            - "node/run"
            - "node/test"
          filters:
            branches:
              only:
                - ci
